version: '3.8'

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 5173:5173
      - 5000:5000
    environment:
      VITE_API_URL: http://localhost:8000

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://db:27017/todo-db
    # volumes:
    #   - ./backend:/app
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo-container
    volumes:
      - todo-db:/data/db

volumes:
  todo-db:
